### ISSUE TITLE
请问如何使用你的库？

### ISSUE THREAD

**Issue by cyysky** [Xiaohui9607/f_anogan_pytorch#1]
成功运行到了你给的步骤，请问下一步我应该如何做？

![Screenshot from 2020-10-18 22-59-31](https://user-images.githubusercontent.com/2968391/96371730-cce08e80-1195-11eb-80f7-f364f480fef0.png)

**Comment by Xiaohui9607** [comment]
你可以写一个脚本把模型加载出来，然后进行预测，我后面会补充上一个example。

**Comment by cyysky** [comment]
谢谢你！🙏
